casbah-ma/hotel-ui

- src/components/Button/Button.stories.jsx
- src/components/CategoriesBar/RoomCategory/index.jsx
- src/components/Modal/index.jsx
- src/components/Navbar/index.jsx
> Fix Build Icons issues

- src/components/Inputs/Input_v2/Input.stories.js
- src/components/Inputs/Input_v2/Input.styles.js
- src/components/Inputs/Input_v2/Input.test.js
- src/components/Inputs/Input_v2/index.jsx
- theme.js
> add input_v2 component

- src/components/Swipers/Swiper_v3/Swiper.stories.js
> Fix Swipers Conflicts

- src/components/GlobalStyles/index.jsx
- src/components/Navbar/Navbar.styles.js
- src/components/Navbar/index.jsx
- src/components/Navbar_v2/Navbar_v2.stories.js
- src/components/Navbar_v2/Navbar_v2.styles.js
- src/components/Navbar_v2/Navbar_v2.test.js
- src/components/Navbar_v2/data.js
- src/components/Navbar_v2/index.jsx
This PR creates the second and third versions of the Navbar.
- Added a new component `<Navbar_v2 />`,.
- Added a `transparent` prop to switch to the third version.
> Navbar v2 and v3

- src/components/Bookings/BookingBar/BookingBar.test.js
- src/components/Bookings/BookingBar_v2/BookingBar.stories.js
- src/components/Bookings/BookingBar_v2/BookingBar.test.js
- src/components/Bookings/BookingBar_v3/BookingBar.stories.js
- src/components/Bookings/BookingBar_v3/BookingBar.styles.js
- src/components/Bookings/BookingBar_v3/BookingBar.test.js
- src/components/Bookings/BookingBar_v3/index.jsx
- src/components/Cards/GuestCard/GuestCard.stories.js
- src/components/Cards/GuestCard/GuestCard.styles.js
- src/components/Cards/GuestCard/GuestCard.test.js
- src/components/Cards/GuestCard/index.jsx
- theme.js
Create a new version of the Booking Bar (V3)
> Booking bar v3

- src/components/Bookings/BookingBar/Bars.jsx
- src/components/Bookings/BookingBar/BookingBar.stories.jsx
- src/components/Bookings/BookingBar_v2/BookingBar.stories.js
- src/components/Bookings/BookingBar_v2/index.jsx
- src/components/Cards/ImageCard/index.jsx
- src/components/Cards/TextCard/index.jsx
- src/components/GlobalStyles/index.jsx
- src/components/Heros/Hero/Hero.styles.js
- src/components/Layout/Layout.stories.jsx
- src/components/Layout/index.jsx
- src/components/Swipers/Swiper_v2/Swiper.styles.js
- src/helpers/generateExports.js
- src/helpers/scriptsHelper.js
- src/pages/Home/index.jsx
- src/styles/global.css
Fix Icons & Nested Folders issues
> Gallery v2

- package.json
- src/components/Bookings/BookingBar/index.jsx
- src/components/CategoriesFilters/CategoriesFilterSpa_v3/index.jsx
- src/components/CategoriesFilters/CategoriesFilter_v2/CategoriesFilter_v2.styles.js
- src/components/CategoriesFilters/CategoriesFilter_v2/index.jsx
- src/components/CategoriesFilters/CategoriesFilter_v3/index.jsx
- src/components/CategoriesFilters/MeetingCategories_v2/MeetingCategories_v2.styles.js
- src/components/CategoriesFilters/MeetingCategories_v2/data.js
- src/components/CategoriesFilters/MeetingCategories_v2/index.jsx
- src/components/FilterBar/CategoryTag/CategoryTag.stories.js
- src/components/FilterBar/CategoryTag/CategoryTag.styles.js
- src/components/FilterBar/CategoryTag/CategoryTag.test.js
- src/components/FilterBar/CategoryTag/index.jsx
- src/components/FilterBar/FilterBar.stories.js
- src/components/FilterBar/FilterBar.styles.js
- src/components/FilterBar/index.jsx
- src/components/Footers/Footer/Footer.styles.js
- src/components/Footers/Footer/index.jsx
- src/components/Masonries/Masonry_v2/data.js
- src/components/Masonries/Masonry_v2/index.jsx
- src/components/Navbars/Navbar_v2/Navbar_v2.styles.js
- src/components/Navbars/Navbar_v2/index.jsx
- src/components/ServicesSection/ServicesSection.stories.js
- src/components/Swipers/Swiper_v2/Swiper.styles.js
- src/helpers/generateExports.js
- src/helpers/scriptsHelper.js
- theme.js
This PR fixes minor UI issues and adds filter functionality to some components.
- Fixed Navbar issues
- Fixed Footer issues
- Change colors to black and white
-  Fixed CategoriesFilter styles
> Fix small UI bugs

- src/components/InfoItems/InfoItem/InfoItem.styles.js
- src/components/InfoItems/InfoItem/InfoItem.test.js
- src/components/InfoItems/InfoItem/index.jsx
- src/components/InfoItems/InfoItems.stories.js
- src/components/Masonries/Masonry/Masonry.stories.js
- src/components/Masonries/Masonry_v2/data.js
- src/components/ServicesGrid/Service/Service.stories.js
- src/components/ServicesGrid/Service/Service.styles.js
- src/components/ServicesGrid/Service/Service.test.js
- src/components/ServicesGrid/Service/index.jsx
- src/components/ServicesGrid/ServicesGrid.stories.js
- src/components/ServicesGrid/ServicesGrid.styles.js
- src/components/ServicesGrid/ServicesGrid.test.js
- src/components/ServicesGrid/index.jsx
- src/components/ServicesSection/ServicesSection.stories.js
- src/components/ServicesSection/index.jsx
This PR adds the second and third versions of the` ServicesGrid`  component.
> Services section

- src/components/Blogs/Blog_v3/Blog_v3.stories.js
- src/components/Blogs/Blog_v4/Blog_v4.stories.js
- src/components/Blogs/Blog_v4/Blog_v4.styles.js
- src/components/Blogs/Blog_v4/Blog_v4.test.js
- src/components/Blogs/Blog_v4/index.jsx
- src/components/Blogs/index.js
- src/components/Cards/RoomCard/RoomCard.stories.js
- src/components/Cards/RoomCard/index.jsx
- src/components/Cards/RoomCard_v2/RoomCard_v2.stories.js
- src/components/Cards/RoomCard_v2/index.jsx
- src/components/Cards/RoomCard_v3/RoomCard_v3.stories.js
- src/components/Cards/RoomCard_v3/index.jsx
- src/components/Cards/TextCard/TextCard.stories.js
- src/components/Cards/TextCard/index.jsx
- src/components/CategoriesFilters/CategoriesFilterSpa_v3/CategoriesFilterSpa_v3.stories.js
- src/components/CategoriesFilters/CategoriesFilterSpa_v3/data.js
- src/components/CategoriesFilters/CategoriesFilterSpa_v3/index.jsx
- src/components/CategoriesFilters/CategoriesFilter_v2/CategoriesFilter_v2.stories.js
- src/components/CategoriesFilters/CategoriesFilter_v2/data.js
- src/components/CategoriesFilters/CategoriesFilter_v2/index.jsx
- src/components/CategoriesFilters/CategoriesFilter_v3/CategoriesFilter_v3.stories.js
- src/components/CategoriesFilters/CategoriesFilter_v3/data.js
- src/components/CategoriesFilters/CategoriesFilter_v3/index.jsx
- src/components/CategoriesFilters/MeetingCategories_v2/MeetingCategories_v2.stories.js
- src/components/CategoriesFilters/MeetingCategories_v2/data.js
- src/components/CategoriesFilters/MeetingCategories_v2/index.jsx
This PR makes the cards clickable to redirect you to their correspondent link.
> Clickable cards

- src/components/Contacts/Contacts.stories.jsx
- src/components/Contacts/Contacts.styles.js
- src/components/Contacts/Contacts.test.js
- src/components/Contacts/index.jsx
- src/components/Forms/Form_v2/Form.styles.js
- src/components/Inputs/Input_v2/Input.styles.js
Restyle input v2
Add version 2 of contact
> restyle input v2 to be just like the design

- src/components/Footers/Footer_v2/Footer.styles.js
- src/components/Footers/Footer_v2/index.jsx
- src/components/FormSection/FormSection.styles.js
- src/components/Forms/Form_v3/Form.stories.js
- src/components/Forms/Form_v3/index.jsx
> restyle footer v2

- src/components/Bookings/BookingBar_v2/index.jsx
- src/components/Navbars/Navbar_v2/index.jsx
> add border to buttons in bookingbar_v2

- src/components/CategoriesFilters/MeetingCategories_v2/data.js
- src/components/CategoriesFilters/MeetingCategories_v2/index.jsx
- src/components/InfoItems/index.jsx
> add title for meetingCategories_v2

- src/components/Blogs/Blog/Blog.styles.js
- src/components/Cards/RoomCard/RoomCard.styles.js
- src/components/CategoriesFilters/CategoriesFilter_v3/CategoriesFilter_v3.styles.js
- src/components/CategoriesFilters/MeetingCategories/MeetingCategories.styles.js
- src/components/CategoriesFilters/MeetingCategories/index.jsx
- src/components/Contacts/Contacts.styles.js
- src/components/Footers/Footer/index.jsx
- src/components/Footers/Footer_v2/index.jsx
- src/components/Forms/Form_v3/Form.styles.js
- src/components/Title/Title.styles.js
> Fix issues kz

- src/components/Bookings/BookingBar_v2/BookingBar.stories.js
- src/components/Bookings/BookingBar_v2/BookingBar.styles.js
- src/components/Button/Button.styles.js
> config some styling issues

- src/components/Blogs/Blog_v3/Blog_v3.styles.js
- src/components/Cards/ImageCard/index.jsx
- src/components/Navbars/Navbar/index.jsx
> Fix issues rb

- src/components/Bookings/BookingBar_v3/index.jsx
> add backlabel

- src/components/Bookings/BookingBar_v2/BookingBar.stories.js
- src/components/Bookings/BookingBar_v3/BookingBar.stories.js
- src/components/Footers/Footer/Footer.stories.jsx
- src/components/Footers/Footer/Footer.styles.js
- src/components/Footers/Footer/index.jsx
- src/components/Heros/Hero/Hero.styles.js
- src/components/Inputs/Input/Input.styles.js
- src/components/Navbars/Navbar_v2/index.jsx
hide and show newsletter and add shapes to footer
> hide and show newsletter and add shapes to footer

- package.json
- src/components/Heros/Hero/Hero.styles.js
- src/components/NotFound/index.jsx
> update component name

- package.json
- src/components/Cards/Card/index.jsx
- src/components/Contacts_v2/ContactsV2.styles.js
- src/components/Contacts_v2/index.jsx
- src/components/Forms/ContactUs/index.jsx
- src/components/Forms/Form_v3/index.jsx
> fix some styling
